/*
巨量方舟

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AgentTicketListV2ResponseData struct for AgentTicketListV2ResponseData
type AgentTicketListV2ResponseData struct {
	Total *int64 `json:"total,omitempty"`
	Data []AgentTicketListV2ResponseDataDataInner `json:"data,omitempty"`
}


