/*
巨量方舟

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// CgCsrfTokenResponse struct for CgCsrfTokenResponse
type CgCsrfTokenResponse struct {
	Code *int64 `json:"code,omitempty"`
	Token *string `json:"token,omitempty"`
	CsrfCode *string `json:"csrf_code,omitempty"`
	CsrfMessage *string `json:"csrf_message,omitempty"`
}


