/*
巨量方舟

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AgentTicketListV2Response struct for AgentTicketListV2Response
type AgentTicketListV2Response struct {
	Code int32 `json:"code"`
	Msg string `json:"msg"`
	Data AgentTicketListV2ResponseData `json:"data"`
}

type _AgentTicketListV2Response AgentTicketListV2Response


