/*
巨量方舟

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AgentTicketListV2ResponseDataDataInner struct for AgentTicketListV2ResponseDataDataInner
type AgentTicketListV2ResponseDataDataInner struct {
	TicketId int32 `json:"ticketId"`
	TicketSubject NullableString `json:"ticketSubject"`
	TicketStatus string `json:"ticketStatus"`
	TemplateName string `json:"templateName"`
	CreatorName string `json:"creatorName"`
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
	CurrentProcessPersons []string `json:"currentProcessPersons"`
	TaskName string `json:"taskName"`
	AdvId NullableInt32 `json:"advId"`
	AdvName NullableString `json:"advName"`
	AgentName string `json:"agentName"`
	AgentId int32 `json:"agentId"`
	AgentCompanyName string `json:"agentCompanyName"`
	AgentCompanyId int32 `json:"agentCompanyId"`
	SalesName string `json:"salesName"`
	SalesDepId int32 `json:"salesDepId"`
	SalesDepName string `json:"salesDepName"`
	ProcessPersons []string `json:"processPersons"`
	TicketStatusName string `json:"ticketStatusName"`
	TicketApp string `json:"ticketApp"`
	AgentSalesId int32 `json:"agentSalesId"`
	AgentSalesName string `json:"agentSalesName"`
	OptimizerId NullableInt32 `json:"optimizerId"`
	OptimizerName NullableString `json:"optimizerName"`
	AthenaOrderId string `json:"athenaOrderId"`
}

type _AgentTicketListV2ResponseDataDataInner AgentTicketListV2ResponseDataDataInner


