/*
巨量方舟

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// TicketListV2Response struct for TicketListV2Response
type TicketListV2Response struct {
	Code *int64 `json:"code,omitempty"`
	Msg *string `json:"msg,omitempty"`
	Data *TicketListV2ResponseData `json:"data,omitempty"`
}


