/*
巨量方舟

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

// AgentTicketListV2ResponseDataDataInner struct for AgentTicketListV2ResponseDataDataInner
type AgentTicketListV2ResponseDataDataInner struct {
	TicketId *int64 `json:"ticketId,omitempty"`
	TicketSubject *string `json:"ticketSubject,omitempty"`
	TicketStatus *string `json:"ticketStatus,omitempty"`
	TemplateName *string `json:"templateName,omitempty"`
	CreatorName *string `json:"creatorName,omitempty"`
	CreateTime *string `json:"createTime,omitempty"`
	UpdateTime *string `json:"updateTime,omitempty"`
	CurrentProcessPersons []string `json:"currentProcessPersons,omitempty"`
	TaskName *string `json:"taskName,omitempty"`
	AdvId *int64 `json:"advId,omitempty"`
	AdvName *string `json:"advName,omitempty"`
	AgentName *string `json:"agentName,omitempty"`
	AgentId *int64 `json:"agentId,omitempty"`
	AgentCompanyName *string `json:"agentCompanyName,omitempty"`
	AgentCompanyId *int64 `json:"agentCompanyId,omitempty"`
	SalesName *string `json:"salesName,omitempty"`
	SalesDepId *int64 `json:"salesDepId,omitempty"`
	SalesDepName *string `json:"salesDepName,omitempty"`
	ProcessPersons []string `json:"processPersons,omitempty"`
	TicketStatusName *string `json:"ticketStatusName,omitempty"`
	TicketApp *string `json:"ticketApp,omitempty"`
	AgentSalesId *int64 `json:"agentSalesId,omitempty"`
	AgentSalesName *string `json:"agentSalesName,omitempty"`
	OptimizerId *int64 `json:"optimizerId,omitempty"`
	OptimizerName *string `json:"optimizerName,omitempty"`
	AthenaOrderId *string `json:"athenaOrderId,omitempty"`
}


